# Generated by Django 5.2.6 on 2026-04-28 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('DETERIORADO', 'Deteriorado'), ('FUERA_SERVICIO', 'Fuera de servicio')], max_length=20)),
                ('codigo', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('foto_1', models.ImageField(blank=True, null=True, upload_to='medidores/')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='medidores/')),
                ('foto_3', models.ImageField(blank=True, null=True, upload_to='medidores/')),
                ('foto_4', models.ImageField(blank=True, null=True, upload_to='medidores/')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_finalizacion', models.TimeField()),
                ('correo', models.EmailField(max_length=254)),
                ('nombre_inspector', models.CharField(max_length=150)),
                ('conclusiones_generales', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InformeTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_informe', models.DateField(auto_now_add=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('medidores', models.ManyToManyField(to='inspecciones.medidor')),
            ],
        ),
        migrations.AddField(
            model_name='medidor',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidores', to='inspecciones.registroinspeccion'),
        ),
    ]
