# Generated by Django 5.0.6 on 2026-05-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroinspeccion',
            name='conclusiones_generales',
        ),
        migrations.RemoveField(
            model_name='registroinspeccion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='registroinspeccion',
            name='fecha_despiece',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroinspeccion',
            name='fecha_informe',
            field=models.DateField(blank=True, null=True),
        ),
    ]
