# Generated by Django 5.2.6 on 2026-05-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroinspeccion',
            name='conclusiones_generales',
        ),
        migrations.RemoveField(
            model_name='registroinspeccion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='registroinspeccion',
            name='fecha_despiece',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroinspeccion',
            name='fecha_informe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='foto_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='foto_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='foto_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medidor',
            name='foto_4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
